GuildOptions:
  NamePattern: "[]"
CommandMessage:
  NoPermission: "&6[&eEpicGuild&6] &c指令权限不足!"
  Help:
    - "&e====== &6[&eEpicGuild &l| &e史诗公会&6] &e======"
    - "&b/guild create [名字] &7创建一个公会"
    - "&b/guild list &7查看所有公会"
    - "&b/guild reload &7重载插件"
  UnknownCommand: "&6[&eEpicGuild&6] &c未知命令!"
  OwnerCantQuitGuild: "&6[&eEpicGuild&6] &c会主不能退出公会!"
  Reload: "&6[&eEpicGuild&6] &a重载成功!"
